# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    machine: true
    working_directory: ~/repo
    environment:
      JAVA_TOOL_OPTIONS: -Djava.net.preferIPv4Stack=true -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:+ExitOnOutOfMemoryError
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: v1-{{ checksum "pom.xml" }}

      # Set up environment
      - run:
          name: Set up environment
          command: |
            echo export KEYCLOAK=OFFICIAL >> $BASH_ENV
            echo export ECHO_ENV=NO >> $BASH_ENV
            echo export UNSET_ENV=NO >> $BASH_ENV
            cat launcher-env-template.sh >> $BASH_ENV
            echo LAUNCHER_MISSIONCONTROL_OPENSHIFT_CLUSTERS_FILE=$(pwd -P)/clusters.yaml >> $BASH_ENV
            echo LAUNCHER_GIT_PROVIDERS_FILE=$(pwd -P)/git-providers.yaml >> $BASH_ENV
          when: always

      - run:
          name: Build project
          command: ./mvnw -V clean install -DskipTests

      - run:
          name: Update Hosts File
          command: |
            echo 8.43.84.242 devtools-dev.ext.devshift.net | sudo tee -a /etc/hosts
            cat /etc/hosts

      # run tests!
      - run:
          name: Run Integration Tests
          command: ./mvnw -V -ff test failsafe:integration-test failsafe:verify -Dfailsafe.rerunFailingTestsCount=2  -Dsurefire.rerunFailingTestsCount=2 -Pit -DfailIfNoTests=false

      - run:
          name: Uninstall artifacts
          command: rm -rf ~/.m2/repository/io/fabric8/launcher
          when: always

      - save_cache:
          paths:
            - ~/.m2
            - ~/.cache/yarn
          key: v1-{{ checksum "pom.xml" }}
          when: always

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always

      - store_test_results:
          path: ~/test-results

      - store_artifacts:
          path: ~/test-results/junit
